### ISSUE TITLE
NoSuchModuleError: Can't load plugin

### ISSUE THREAD

**Issue by viswanathvs1981** [preset-io/elasticsearch-dbapi#11]
Hi,

I am consistently getting an error after following the installation steps when i try to test the connection from superset. 

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nCan't load plugin: sqlalchemy.dialects:elasticsearch.https", 

We are leveraging the aws elasticsearch service and the sqlalchemy url we are trying to hit is 
elasticsearch+https://elastic:changeme@search-xxxxx.xxxx.es.amazonaws.com:9200/

Please suggest

Best
Viswanath Sekar

**Comment by viswanathvs1981** [comment]
@dpgaspar 
Hi,
Although i was able resolve the above issue i am now consistently getting an access denied exception when trying to connect to aws elasticsearch service. The service is temporarily public to test connectivity . 
Appreciate all your help in this regard.

The url format in superset and error details are below
elasticsearch+https://search-yyyyyyyyyyyyyyyyyyyyyyyyy.us-uuuuu-1.es.amazonaws.com:443/

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nAuthenticationException(401, '{\"Message\":\"Your request: \\'/_sql/\\' is not allowed.\"}')", "stacktrace": "Traceback (most recent call last):\n  File \"/home/superset/superset/views/core.py\

**Comment by dpgaspar** [comment]
Hi @viswanathvs1981,

Very limited support for AWS ES you will not be able to perform most of superset features, AWS auth is not supported
