### ISSUE TITLE
Able to connect but not query Elasticsearch from Superset

### ISSUE THREAD

**Issue by akki** [preset-io/elasticsearch-dbapi#13]
Hi

I am able to add Elasticsearch as a data source in Superset and the "test connection" works for me.

But when I try to query my data in the SQL Lab of Superset's UI, it gives me error `This is a readonly dbapi commit is not supported`. I am running the SELECT query - `SELECT * FROM children_test;` (please note that I am not running any commits).

Also, it doesn't show anything when I try to view schema from the panel in the left.

Attaching screenshot for reference:
<img width="1358" alt="Screen_Shot_2020-03-12_at_00_04_46" src="https://user-images.githubusercontent.com/4801628/76444277-4b05d700-63f6-11ea-84e6-895bb3777051.png">

Can you please help me with what I am doing wrong over here? Any help would be greatly appreciated.

**Comment by willbarrett** [comment]
This looks like a question for @dpgaspar or @villebro .

**Comment by akki** [comment]
I found the origin of the problem. It's pretty simple actually:

[Apache-Superset](https://github.com/apache/incubator-superset/) commits to the database on [this line](https://github.com/apache/incubator-superset/blob/f6f40c815a9ed962d5bbbf9dd4fb357479bd3677/superset/sql_lab.py#L389).
Which calls [this line](https://github.com/preset-io/elasticsearch-dbapi/blob/9aff5e4f6459fba4ea9cc244196f792b5ff36582/es/baseapi.py#L83) of `elasticsearch-dbapi` which throws an error.

This is what is happening as per my understanding:
 - Superset commits *any* query it gets (regardless of it being a write query or not) to the database.
 - The `elasticsearch-dbapi` is a read-only driver, hence doesn't expect anyone to call their `commit` method - Afterall why would someone commit something to the database (ES in this case) when they aren't writing/updating/inserting anything to it.
<br />

So probably it is something that should be fixed in Apache-superset?

**Comment by dpgaspar** [comment]
Hi @akki,

Good troubleshooting, or change on superset on simply ignore commit's on elasticsearch dbapi, since they don't make sense on elasticsearch.

**Comment by akki** [comment]
@dpgaspar Thanks for your suggestion.

As far as I looked into the Superset code I did not see any custom logic written for particular databases, at least not in this part of the code of superset. So I don't think it would be possible (or at least easy to add a logic saying "if it is es, then ignore it"). I did not have too deep dives into the code though, so I might be missing something here.

Also, I realised if superset's code works for other databases, it means they allow such commits even if the queries are read-only.
So, it might not be wrong to just `pass` in the [`commit method`](https://github.com/preset-io/elasticsearch-dbapi/blob/9aff5e4f6459fba4ea9cc244196f792b5ff36582/es/baseapi.py#L77) instead of raising a `NotSupportedError`.

**Comment by villebro** [comment]
@akki I tend to agree with your assessment of just passing on `commit()`. If not we could also add an engine parameter to explicitly ignore commit errors, but that feels slightly overkill, and best stated explicitly in the documentation. @dpgaspar do you agree?

**Comment by dpgaspar** [comment]
Agree @villebro

**Comment by akki** [comment]
Okay, created a PR - https://github.com/preset-io/elasticsearch-dbapi/pull/16

**Comment by dpgaspar** [comment]
The fix is out now, checkout elasticsearch-dbapi 0.1.1

Thank you for reporting this and the PR ;) opensource FTW
