### ISSUE TITLE
Elasticsearch query return the {e} in result

### ISSUE THREAD

**Issue by ankur-vyas14** [preset-io/elasticsearch-dbapi#27]
I am able to connect the Elasticsearch with the Apache Superset and it also shows the the table in the left panel. But when I am trying to fire the query on the table it returns the {e} as a result.

Environment
superset version: 0.36.0
python version: 3.7
elasticsearch version: 7.6.2
elasticsearch-dbapi: 0.1.2

![es-error](https://user-images.githubusercontent.com/41239909/81635997-52665280-9430-11ea-891e-5155fe1fb5f9.PNG)

**Comment by dpgaspar** [comment]
@ankur-vyas14, thks for opening this here, will try to reproduce this now. Can you add your server logs?

**Comment by dpgaspar** [comment]
Wasn't able to reproduce it yet, tried a bunch of queries that fail but the error message looks good:

<img width="1200" alt="Screenshot 2020-05-12 at 10 37 44" src="https://user-images.githubusercontent.com/4025227/81668707-f6ee9180-943c-11ea-935b-807499c9943a.png">

Post the server logs when the error occurs, please

**Comment by ankur-vyas14** [comment]
Hey @dpgaspar Thanks for your advice for looking into log. There is one module error after fixing that query seems to work.
![es-working-query](https://user-images.githubusercontent.com/41239909/81674902-8f9c0600-946b-11ea-82c1-d156b4863d96.PNG)


Just a question here is **SELECT * FROM TABLE** statement is not supported in elastic search? Because when we provide the column name query seems to work but in select * statement it returns the error. 
![es-not-working](https://user-images.githubusercontent.com/41239909/81674976-ae9a9800-946b-11ea-9fc1-488794d318f8.PNG)

**Comment by dpgaspar** [comment]
`SELECT *` is supported by elasticsearch, the problem is related with an array type column. note that not all columns are selected on the column name query
