### ISSUE TITLE
Opendistro: Authentication 

### ISSUE THREAD

**Issue by igorpereirabr1** [preset-io/elasticsearch-dbapi#29]
Hey Guys.. I'm to try connect the Apache Superset at my Opendistro cluster, But I'm not to sure how to include the user and password here: odelasticsearch+https://search-SOME-CLUSTER.us-west-2.es.amazonaws.com:443/

Any idea?

**Comment by willbarrett** [comment]
Hi @igorpereirabr1 - let me take a look and get back to you.

**Comment by igorpereirabr1** [comment]
Thanks bufou!

**Comment by dpgaspar** [comment]
Note: Open distro is not well supported, but for basic Auth should be: `odelasticsearch+https://<USER>:<PASSWORD>@search-SOME-CLUSTER.us-west-2.es.amazonaws.com:443/`

**Comment by igorpereirabr1** [comment]
Thanks! I'll test!
