### ISSUE TITLE
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:elasticsearch.http

### ISSUE THREAD

**Issue by imranmasood** [preset-io/elasticsearch-dbapi#36]
I am trying to connect to Elasticsearch using SQLAlchemy and I get this error

connection_es=create_engine("elasticsearch+http://elastic:changeme@localhost:9200/")

---------------------------------------------------------------------------
NoSuchModuleError                         Traceback (most recent call last)
<ipython-input-31-d4a9c45e7426> in <module>
      2 ## format of connection string is:
      3 ## "dialect://username:password@host:port/"
----> 4 connection_es=create_engine("elasticsearch+http://elastic:changeme@localhost:9200/")

~/.pyenv/versions/myEnv/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py in create_engine(*args, **kwargs)
    498     strategy = kwargs.pop("strategy", default_strategy)
    499     strategy = strategies.strategies[strategy]
--> 500     return strategy.create(*args, **kwargs)
    501 
    502 

~/.pyenv/versions/myEnv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py in create(self, name_or_url, **kwargs)
     59         kwargs.pop("plugins", None)
     60 
---> 61         entrypoint = u._get_entrypoint()
     62         dialect_cls = entrypoint.get_dialect_cls(u)
     63 

~/.pyenv/versions/myEnv/lib/python3.8/site-packages/sqlalchemy/engine/url.py in _get_entrypoint(self)
    170         else:
    171             name = self.drivername.replace("+", ".")
--> 172         cls = registry.load(name)
    173         # check for legacy dialects that
    174         # would return a module with 'dialect' as the

~/.pyenv/versions/myEnv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py in load(self, name)
    266                 return impl.load()
    267 
--> 268         raise exc.NoSuchModuleError(
    269             "Can't load plugin: %s:%s" % (self.group, name)
    270         )

NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:elasticsearch.http

[-]
pip show elasticsearch-dbapi                                                                                                                          
Name: elasticsearch-dbapi
Version: 0.1.3
Summary: A DBAPI and SQLAlchemy dialect for Elasticsearch
Home-page: http://preset.io
Author: Preset Inc.
Author-email: daniel@preset.io
License: Apache License, Version 2.0
Location: /Users/masoodimran/.pyenv/versions/3.8.6/envs/myEnv/lib/python3.8/site-packages
Requires: elasticsearch, sqlalchemy
Required-by: 

Name: SQLAlchemy
Version: 1.3.20
Summary: Database Abstraction Library
Home-page: http://www.sqlalchemy.org
Author: Mike Bayer
Author-email: mike_mp@zzzcomputing.com
License: MIT
Location: /Users/masoodimran/.pyenv/versions/3.8.6/envs/myEnv/lib/python3.8/site-packages
Requires: 
Required-by: elasticsearch-dbapi

Python: 3.8.6

**Comment by dpgaspar** [comment]
That's strange, but can't reproduce

On a new environment:
```
pip freeze
certifi==2020.11.8
elasticsearch==7.10.0
elasticsearch-dbapi==0.1.3
six==1.15.0
SQLAlchemy==1.3.20
urllib3==1.26.2
```

```
Python 3.6.10 (default, Apr  1 2020, 00:02:47)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.29)] on XXXX
Type "help", "copyright", "credits" or "license" for more information.
>>> from sqlalchemy.engine import create_engine
>>>
>>> engine = create_engine("elasticsearch+http://localhost:9200/")
>>> engine = create_engine("elasticsearch+http://username:password@localhost:9200/")
>>>
```
