### ISSUE TITLE
Changes in `get_table_names` cause performance hit

### ISSUE THREAD

**Issue by Alexander-N** [preset-io/elasticsearch-dbapi#43]
Thanks a lot for fixing #38, I really appreciate the active maintenance of this project!

Unfortunately, this [ change ](https://github.com/preset-io/elasticsearch-dbapi/commit/8c1bb376b3e0c337fc4e1a68a9aaababc8011db6#diff-fd49e674d6b336bf0ffa19f87bf93f3432534014f06c66aeb8098498082b3dd5)  to `get_table_names` which seems unrelated to fixing #38 degrades the performance a lot since the calls of `get_columns` cause one additional request per table. It can also trigger a lot of warnings since `get_type` is called in `get_columns`.

This also affects `has_table` which prevents me from upgrading to the newest version of elasticsearch-dbapi.

Maybe this change can be reverted or solved in some other way? Simply adding an `lru_cache` decorator could also be an option.

**Comment by dpgaspar** [comment]
ok, thank you for reporting. I'll fix it ASAP

**Comment by dpgaspar** [comment]
Made an initial quick fix (trying not to revert). Would be great if you could test it @Alexander-N

**Comment by dpgaspar** [comment]
A fix is already on master, can you test it please?

**Comment by Alexander-N** [comment]
Works fine, thanks @dpgaspar!
