### ISSUE TITLE
Reflection of table names fails for new releases

### ISSUE THREAD

**Issue by Alexander-N** [preset-io/elasticsearch-dbapi#52]
The tables collection of the `MetaData` object is empty after updating elasticsearch-dbapi. It seems like the regression was introduced with https://github.com/preset-io/elasticsearch-dbapi/commit/654dcd3e8c435cf039df690ea66cc7202da8bbe7 where the following code fails:

```python
from sqlalchemy import MetaData, create_engine

engine = create_engine(database_uri)
meta = MetaData()
meta.reflect(bind=engine)
assert len(meta.tables) > 0
```

It does not fail at https://github.com/preset-io/elasticsearch-dbapi/commit/916d1ded21224c5d8d9ebdff9466c76325b02001.

**Comment by dpgaspar** [comment]
Hi @Alexander-N is this with opendistro or elasticsearch, can you post the stack trace?

**Comment by Alexander-N** [comment]
This is with elasticsearch. `meta.tables` is just empty so there is no error other than the failed assertion.

**Comment by dpgaspar** [comment]
no errors?

Did a quick test with:
```
from sqlalchemy import MetaData, create_engine



uris = [
    "odelasticsearch+https://admin:admin@localhost:19200/?verify_certs=False",
    "elasticsearch+http://localhost:9200/",
]

for uri in uris:
    engine = create_engine(uri)
    meta = MetaData()
    meta.reflect(bind=engine)
    print(len(meta.tables))
    print(meta.tables)
```
Using repo's docker-compose and I get no errors, again is this opendistro or elasticsearch? can you share your index schema?

**Comment by Alexander-N** [comment]
Could it be related to aliases? I have for example indices like `sales_master_2021-03-22_05-27-09` but only access them with aliases, for example `sales_master`.

**Comment by dpgaspar** [comment]
if you connection user does not have access to `sales_master_2021-03-22_05-27-09` it could explain it, or if the index is empty

```
from sqlalchemy import MetaData, create_engine
from sqlalchemy.engine.reflection import Inspector



uris = [
    "odelasticsearch+https://admin:admin@localhost:19200/?verify_certs=False",
    "elasticsearch+http://localhost:9200/",
]

for uri in uris:
    engine = create_engine(uri)
    meta = MetaData()
    meta.reflect(bind=engine)
    inspector = Inspector.from_engine(engine)
    tables = inspector.get_table_names("default")
    views = inspector.get_view_names("default")
    print(tables)
    print(views)
```

**Comment by Alexander-N** [comment]
That was the problem, thanks! Since the views and tables were split in https://github.com/preset-io/elasticsearch-dbapi/commit/654dcd3e8c435cf039df690ea66cc7202da8bbe7 `meta.tables` is now empty for me unless I use `views=True` option in
```python
meta.reflect(bind=engine, views=True)
```
.

**Comment by dpgaspar** [comment]
Thank you for double checking!

**Comment by Alexander-N** [comment]
Closed it a bit too early. Now I get all views, but still not the tables. The reason seems to be that the type in `result[1]` is `TABLE` instead of `BASE TABLE` in my case (elasticsearch version 7.11.1).

https://github.com/preset-io/elasticsearch-dbapi/blob/654dcd3e8c435cf039df690ea66cc7202da8bbe7/es/elastic/api.py#L89-L115

**Comment by dpgaspar** [comment]
I run my tests on ES 7.3 let me check if that changed

**Comment by dpgaspar** [comment]
Just confirmed it changed on 7.10.X, I'll make a solution for it

**Comment by dpgaspar** [comment]
@Alexander-N support for elasticsearch > 7.10 is merged on master. 0.2.2 will be out soon

**Comment by dpgaspar** [comment]
ok it's out now, going to close this issue, thank you again for reporting and helping on troubleshooting

**Comment by Alexander-N** [comment]
Works fine, thanks @dpgaspar!
