### ISSUE TITLE
elastic db api not working in superset

### ISSUE THREAD

**Issue by shashankkoppar** [preset-io/elasticsearch-dbapi#59]
There are no tables in option when i select elasticsearch dataset 
![Screenshot 2021-04-23 at 12 35 46](https://user-images.githubusercontent.com/14154688/115859462-87e13180-a430-11eb-9865-a8d61a1406cf.png)

I saw this error as well 
```
elasticsearch error: TransportError(500, 'ql_illegal_argument_exception', 'Arrays (returned by [doc.categories.color]) are not supported')
```

Superset version: 0.38.0
Elastic search version: 7.8.0
elastic-db-api version: 0.2.3 

Any leads will be really helpful. We are facing this issue since we upgraded elastic search.

**Comment by shashankkoppar** [comment]
@dpgaspar , Would appreciate if you take a look and see whats going wrong?

**Comment by dpgaspar** [comment]
Is this elasticsearch or AWS opendistro?

**Comment by shashankkoppar** [comment]
its elastic search running on google cloud vms

**Comment by dpgaspar** [comment]
ok, and this occurred after upgrading your elasticsearch cluster not the dbapi, right?

**Comment by shashankkoppar** [comment]
yes true, after we upgraded our elastic search from 6.8.0, we are not able to connect to it.

**Comment by dpgaspar** [comment]
@shashankkoppar I was able to reproduce, so if you create an index with an array (assuming that your index has some array type fields):

``` json
PUT my_index_000001/_doc/1
{
  "message": "some arrays in this document...",
  "tags":  [ "elasticsearch", "wow" ], 
  "lists": [ 
    {
      "name": "prog_list",
      "description": "programming list"
    },
    {
      "name": "cool_list",
      "description": "cool stuff list"
    }
  ]
}
```

Then if you issue a SQL query on the elasticsearch endpoint, example:
```
POST /_sql
{
  "query": "select * from my_index_000001"
}

```

You get:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "ql_illegal_argument_exception",
        "reason" : "Arrays (returned by [lists.description]) are not supported"
      }
    ],
    "type" : "ql_illegal_argument_exception",
    "reason" : "Arrays (returned by [lists.description]) are not supported"
  },
  "status" : 500
}
```

So, it's actually an Elasticsearch limitation, arrays are not supported for SQL queries, you can still use the index by selecting non array columns:

``` json
POST /_sql
{
  "query": "select message from my_index_000001"
}
```

Or creating an alias to the index

**Comment by shashankkoppar** [comment]
Hey thanks for checking @dpgaspar. I checked and it works fine for non array columns in Superset SQL query as well. But only issue now is it is not able list tables there when you select elastic-search as database and not possible to add any datasets. Do you do any kind of tests if db-api works properly in superset though? :D

**Comment by dpgaspar** [comment]
Closing this one, feel free to reopen
