### ISSUE TITLE
Elasticsearch-dbapi does not support Elasticsearch 6.8 and only supports 7.x or above？

### ISSUE THREAD

**Issue by wwwDengJXcom** [preset-io/elasticsearch-dbapi#61]
Just like the title，Looking forward to your reply，thank

**Comment by dpgaspar** [comment]
It's tested with elasticsearch 7.3.2. May work with 6.8 if there's a SQL endpoint already (not officially supported)

**Comment by wwwDengJXcom** [comment]
I see, thanks for your reply

**Comment by dpgaspar** [comment]
np, thanks for reaching out. Closing this now
