### ISSUE TITLE
Run query in opendistro with apache-superset's logged in user privliges

### ISSUE THREAD

**Issue by syamat** [preset-io/elasticsearch-dbapi#63]
I have configured some Document Level Security based on the user which accesses the data. Is it possible to run a query on ODE using the same user as the one logged into the apache-superset even though the connection string uses "admin" user to connect to the ODE instance.?

**Comment by dpgaspar** [comment]
@syamat good question, I think currently it's not possible (but not sure). This is a question for Apache Superset not the driver itself.

**Comment by syamat** [comment]
No, it is not possible, I tried. We will have to create multiple database connection with the respective users and use that connection to get the result. So it seems opendistro uses the same user as the one in the connection url.

So should I go ahead and file a issue under Apache Superset ?
