### ISSUE TITLE
Support SQL query params in ES official document

### ISSUE THREAD

**Issue by youngsol** [preset-io/elasticsearch-dbapi#68]
https://github.com/preset-io/elasticsearch-dbapi/blob/ea7a09370d537db88392d8bcadfc081ea05bef6b/es/baseapi.py#L311

do you plan to support additional params such as "time_zone" listed in this [official docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-search-api.html)?

In superset, you can query the data based on the timezone set in request body and this can be set via engine params in superset shown below

![image](https://user-images.githubusercontent.com/4494723/132787178-c9908554-29f7-4f4b-bc0a-915877ce059a.png)

**Comment by dpgaspar** [comment]
`fetch_size` already exists and `time_zone` is about to be merged: https://github.com/preset-io/elasticsearch-dbapi/pull/69
