### ISSUE TITLE
Elasticsearch - Apache Superset not connecting to OSS version of ES.

### ISSUE THREAD

**Issue by syamat** [preset-io/elasticsearch-dbapi#7]
Apache Superset not connecting to OSS version of ES. Using ES v 7.5

ERROR: {"error": "Connection failed!\n\nThe error message returned was:\nTransportError(405, 'Incorrect HTTP method for uri [/_sql/] and method [POST], allowed: [GET, PUT, DELETE, HEAD]', 'Incorrect HTTP method for uri [/_sql/] and method [POST], allowed: [GET, PUT, DELETE, HEAD]')", "stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/superset/views/core.py\", line 1772, in testconn\n    conn.scalar(select([1]))\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 920, in scalar\n    return self.execute(object_, *multiparams, **params).scalar()\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 988, in execute\n    return meth(self, multiparams, params)\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py\", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1107, in _execute_clauseelement\n    distilled_params,\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1248, in _execute_context\n    e, statement, parameters, cursor, context\n  File \"/usr/local/AT_Dev_Env/AmritaTech/apache-superset/master/incubator-superset/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line ...
![OpenDistro_Superset_Error_4](https://user-images.githubusercontent.com/10418735/71303401-234a3880-23de-11ea-8b0d-5b8b515b2e31.png)

**Comment by dpgaspar** [comment]
Hi @syamat,

Are you trying to use the `elasticsearch` driver with the elasticsearch opendistro version?

If yes, it will not work they use different endpoints for SQL and their responses are different

**Comment by syamat** [comment]
No, I have connected ES 7.5 OSS version only. Please see the screenshot
![ES_7 5_OSS](https://user-images.githubusercontent.com/10418735/71505501-6e16f500-28a3-11ea-9fc2-9d371b98fb9a.png)
![ES_7 5_OSS_Superset_Error](https://user-images.githubusercontent.com/10418735/71505551-9d2d6680-28a3-11ea-8229-078b089b6003.png)

**Comment by dpgaspar** [comment]
Can you make the following test and post the result:
```
curl -X POST http://localhost:9200/_sql -d '{"query": "SELECT 1"}' -H 'Content-Type: application/json'
```

**Comment by vinograt** [comment]
> Can you make the following test and post the result:
> 
> ```
> curl -X POST http://localhost:9200/_sql -d '{"query": "SELECT 1"}' -H 'Content-Type: application/json'
> ```

got the same error:
```
curl -X POST http://localhost200/_sql -d '{"query": "SELECT 1"}' -H 'Content-Type: application/json'

{"error":"Incorrect HTTP method for uri [/_sql] and method [POST], allowed: [PUT, DELETE, GET, HEAD]","status":405}
```

**Comment by vinograt** [comment]
> Are you trying to use the `elasticsearch` driver with the elasticsearch opendistro version?
> 
> If yes, it will not work they use different endpoints for SQL and their responses are different

What version should be used?

**Comment by bawantha** [comment]
any solutions ???

**Comment by dioptre** [comment]
+1

**Comment by dioptre** [comment]
Turns out you need to install the SQL plugin (but wasn't working for 6.8.4 for me). https://github.com/NLPchina/elasticsearch-sql/ mentions x-pack-sql and opendistro
https://opendistro.github.io/for-elasticsearch-docs/docs/sql/
