### ISSUE TITLE
dependency 'packaging' should be upgraded

### ISSUE THREAD

**Issue by shawnzhu** [preset-io/elasticsearch-dbapi#76]
when installing superset with elasticsearch client via:

```SHELL
pip3 install apache-superset[db2,druid,elasticsearch]==1.3.2
```

I got error message:

```
ERROR: elasticsearch-dbapi 0.2.6 has requirement packaging==21.0, but you'll have packaging 21.3 which is incompatible.
```

Then I found the dependency `packaging` installation is introduced by `bleach` (dependency of superset): https://github.com/apache/superset/blob/7353a2bd75ae5c76458615443f530a688e78db1c/setup.py#L68 where it doesn't lock down version:

https://github.com/mozilla/bleach/blob/a362171055af36996dc1cedb64c6b3f68359db27/setup.py#L11

## Options

I can try to lock down `packaging==21.0` prior to the installation of `apache-superset[elasticsearch]` to avoid conflict, then it will lead me to lock down `pyparsing==2.4.7` prior to the installation of `packaging==21.0`.

It would be easier if it upgrades `packaging` in this package or just don't lock down its release.

**Comment by dpgaspar** [comment]
merged a fix, I'll release soon

**Comment by shawnzhu** [comment]
@dpgaspar thank you!
